version: '3'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password1
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo:4.4.24
    ports:
      - 27017:27017
